services:
    iris:
      build: .
      container_name: ogs-iris
      restart: always
      ports:
        - "1972:1972"
        - "52773:52773"
      environment:
        - ISC_DATA_DIRECTORY=/external/durable        
      volumes:
        - ${PATH_TO_PROJECT}/external/durable:/external/durable