Class GroceryApp.utils.Constants Extends %RegisteredObject
{

Parameter REGIONS = "EU,NA,APAC,LATAM,MEA,ANZ,SA,EE";

Parameter REGIONCLASSNAME = "GroceryApp.data.Region";

Parameter REGIONTABLENAME = "GroceryApp_data.Region";

Parameter LOGINPAGENAME = "GroceryApp.pages.auth.LoginPage.cls";

Parameter LOGOUTPAGENAME = "#";

Parameter REGISTERPAGENAME = "GroceryApp.pages.auth.RegisterPage.cls";

Parameter PRODUCTLISTPAGENAME = "#";

Parameter ORDERLISTPAGENAME = "#";

Parameter USERMANAGEPAGENAME = "#";

Parameter MANAGEPRODUCTPAGENAME = "#";

Parameter CARTPAGENAME = "#";

Parameter ACCESSDENIEDPAGENAME = "#";

Parameter SECURITYUSERTABLENAME = "%SYS.User";

// Стандартная таблица пользователей в IRIS

Parameter LOGINFAILERR = "LOGIN_FAILED";

Parameter LOGOUTSUCCESS = "LOGOUT_SUCCESS";

Parameter INVALIDREGIONERR = "INVALID_REGION";

Parameter MISSINGFIELDSERR = "MISSING_LOGIN_OR_PASSWORD";

}
