zn "APP"

// Загрузка всех классов в APP namespace
do $System.OBJ.LoadDir("/opt/irisapp/src", "cuk","",1)

// Сидирование данных
try {
    write !, "Seeding region data...", !
    do ##class(GroceryApp.utils.Seed).SeedRegions()
    write !, "Seeding completed successfully!", !
} catch ex {
    write !, "Error during seeding regions: ", ex.DisplayString(), !
}

set stmt = ##class(%SQL.Statement).%New()
do stmt.%Execute("GRANT SELECT ON TABLE GroceryApp_data.Region TO GroceryAppUnknownUser")

zn "%SYS"

do ##class(Security.Users).AddRoles("UnknownUser", "GroceryAppUnknownUser", 1)
do ##class(Security.Users).AddRoles("SuperUser", "%all, CustomAdmin", 1)

halt